## reactions_table.jl - GENERATED by build_reactions50.py. Do not edit by hand.
## 50 representative organic electrosyntheses, stratified by the 25,941-rxn corpus.
struct OERxn
    cls::String
    name::String
    carrier::String
    D::Float64      # m^2/s
    C::Float64      # mol/m^3 (carrier)
    n::Float64      # e- per carrier turnover
    nu::Float64     # solvent kinematic viscosity m^2/s
    Csub::Float64   # mol/m^3 substrate
    nsub::Float64
end

const RXNS = OERxn[
    OERxn("C-N formation", "Ni-catalyzed aryl amination (ArBr + amine)", "catalyst", 2.5184e-10, 5.0, 2.0, 2.0566e-06, 50.0, 2.0),
    OERxn("C-N formation", "Electrochemical amination of ArX with NH3", "catalyst", 3.1309e-10, 5.2, 2.0, 1.4623e-06, 104.0, 2.0),
    OERxn("C-O formation", "Shono oxidation (N-acyliminium capture)", "substrate", 1.2613e-09, 1560.0, 2.0, 6.9211e-07, 1560.0, 2.0),
    OERxn("Cyclization", "Oxidative benzimidazole annulation (C-H/N-H)", "substrate", 1.3677e-09, 33.0, 2.0, 5.5363e-07, 33.0, 2.0),
    OERxn("C-N formation", "Mn-catalyzed alkene diazidation", "catalyst", 1.4796e-09, 2.6, 1.0, 4.7552e-07, 51.0, 2.0),
    OERxn("Functional group intraconversion", "Br-mediated Hofmann rearrangement", "mediator", 2.7000e-09, 80.0, 1.0, 4.7552e-07, 400.0, 2.0),
    OERxn("C-N formation", "Arene C-H pyridination", "substrate", 2.1082e-09, 20.0, 2.0, 4.7552e-07, 20.0, 2.0),
    OERxn("Cyclization", "Amidyl-radical C-H amination (phenanthridinone)", "substrate", 1.4129e-09, 40.0, 2.0, 4.7552e-07, 40.0, 2.0),
    OERxn("Cyclization", "Co-catalyzed aza-Wacker cyclization", "catalyst", 1.1836e-09, 3.3, 1.0, 4.7552e-07, 33.0, 2.0),
    OERxn("C-N formation", "Ritter-type C(sp3)-H amination", "substrate", 1.5639e-09, 167.0, 2.0, 4.7552e-07, 167.0, 2.0),
    OERxn("C-N formation", "Co-H alkene reduction (e-HAT)", "catalyst", 9.5782e-10, 8.0, 1.0, 5.1642e-07, 80.0, 2.0),
    OERxn("C-C formation", "Kolbe homocoupling of 10-undecenoate", "substrate", 2.0109e-09, 1000.0, 1.0, 3.9031e-07, 1000.0, 1.0),
    OERxn("C-C formation", "Ni-XEC C(sp2)-C(sp3) (ArBr + RBr)", "catalyst", 2.5184e-10, 15.0, 2.0, 2.0566e-06, 300.0, 2.0),
    OERxn("C-C formation", "Doubly decarboxylative Csp3-Csp3", "substrate", 8.2376e-10, 29.0, 1.0, 8.4110e-07, 29.0, 1.0),
    OERxn("C-C formation", "BDD phenol-arene cross-coupling", "substrate", 8.5623e-10, 150.0, 2.0, 1.0144e-06, 150.0, 2.0),
    OERxn("C-C formation", "Decarboxylative Minisci alkylation", "substrate", 1.8997e-09, 80.0, 1.0, 4.7552e-07, 80.0, 1.0),
    OERxn("C-C formation", "Cathodic Giese (R-I + alkene)", "substrate", 1.0055e-09, 95.0, 1.0, 9.5745e-07, 79.0, 1.0),
    OERxn("C-C formation", "Rh-catalyzed electrooxidative C-H alkenylation", "catalyst", 1.7332e-10, 3.1, 2.0, 3.2941e-06, 125.0, 2.0),
    OERxn("C-C formation", "Cu-catalyzed benzylic cyanation", "catalyst", 1.4796e-09, 3.8, 1.0, 4.7552e-07, 38.0, 2.0),
    OERxn("C-C formation", "Cathodic Ni aryl-aryl homocoupling", "catalyst", 6.7496e-10, 30.0, 2.0, 9.1476e-07, 300.0, 2.0),
    OERxn("C-C formation", "Anodic dehydrogenative 2-naphthol coupling", "substrate", 1.8582e-09, 1000.0, 1.0, 4.7552e-07, 1000.0, 1.0),
    OERxn("C-C formation", "Acrylonitrile hydrodimerization (ADN)", "substrate", 1.3138e-09, 6850.0, 1.0, 8.9268e-07, 6850.0, 1.0),
    OERxn("Reduction", "Birch reduction of naphthalene", "substrate", 2.0523e-09, 141.0, 2.0, 5.1642e-07, 141.0, 2.0),
    OERxn("Reduction", "Nitroarene -> aniline", "substrate", 4.6983e-10, 400.0, 6.0, 1.8391e-06, 400.0, 6.0),
    OERxn("Reduction", "Rapid-alternating-polarity imide reduction", "substrate", 1.4893e-09, 33.3, 4.0, 6.9211e-07, 33.3, 4.0),
    OERxn("Multicomponent coupling", "Diazo difunctionalization (thiol + alcohol)", "substrate", 2.1495e-09, 77.0, 2.0, 4.7552e-07, 77.0, 2.0),
    OERxn("Functional group intraconversion", "Cathodic aryl chloride dehalogenation", "substrate", 1.9222e-09, 43.0, 2.0, 4.7552e-07, 43.0, 2.0),
    OERxn("Reduction", "Benzaldehyde -> benzyl alcohol", "substrate", 5.6322e-10, 20.0, 2.0, 1.8391e-06, 20.0, 2.0),
    OERxn("Oxidation", "ACT-mediated alcohol oxidation (flow, hectogram)", "mediator", 5.9273e-10, 25.0, 1.0, 8.9268e-07, 500.0, 2.0),
    OERxn("C-O formation", "Anodic methoxylation of 4-tBu-toluene (Lysmeral)", "substrate", 1.2904e-09, 810.0, 4.0, 6.9211e-07, 810.0, 4.0),
    OERxn("C-O formation", "Shono alpha-methoxylation of amides", "substrate", 1.3944e-09, 1560.0, 2.0, 6.9211e-07, 1560.0, 2.0),
    OERxn("Oxidation", "Cl-mediated ethylene epoxidation", "mediator", 2.0300e-09, 1000.0, 1.0, 8.9268e-07, 3.5, 2.0),
    OERxn("Unclassified", "Alkaline lignin -> vanillin (pilot)", "substrate", 9.2000e-10, 1000.0, 1.0, 8.9268e-07, 1000.0, 1.0),
    OERxn("Oxidation", "Thioether -> sulfone (kilo-scale)", "substrate", 1.5220e-09, 470.0, 4.0, 5.8537e-07, 470.0, 4.0),
    OERxn("Oxidation", "NHPI-mediated allylic C-H -> enone", "mediator", 2.0936e-09, 33.0, 1.0, 3.9031e-07, 167.0, 4.0),
    OERxn("Multicomponent coupling", "Alkenesulfonate from cinnamic acid, SO2 and alcohol", "substrate", 1.8307e-09, 100.0, 1.0, 4.7552e-07, 100.0, 2.0),
    OERxn("Oxidation", "HMF -> FDCA (biomass)", "mediator", 5.9273e-10, 40.0, 1.0, 8.9268e-07, 100.0, 6.0),
    OERxn("Cyclization", "Radical-cation Diels-Alder (catalytic in e-)", "substrate", 1.2136e-09, 80.0, 0.1, 5.4529e-07, 80.0, 0.1),
    OERxn("C-O formation", "BQ-mediated Wacker-Tsuji oxidation", "mediator", 1.7797e-09, 23.5, 2.0, 5.8537e-07, 118.0, 2.0),
    OERxn("Functional group intraconversion", "Non-Kolbe decarboxylative alpha-methoxylation", "substrate", 1.2695e-09, 100.0, 2.0, 6.9211e-07, 100.0, 2.0),
    OERxn("Isomerization", "Co-H alkene isomerization (catalytic)", "catalyst", 1.4273e-09, 4.8, 0.2, 3.9031e-07, 80.0, 0.2),
    OERxn("Cyclization", "Anodic oxazoline/oxazole cyclization", "substrate", 1.9719e-09, 50.0, 2.0, 4.7552e-07, 50.0, 2.0),
    OERxn("Cyclization", "Cathodic aryl-halide radical 5-exo cyclization", "catalyst", 6.1120e-10, 10.0, 1.0, 8.4110e-07, 50.0, 1.0),
    OERxn("Cyclization", "Dehydrogenative lactonization (C-H/O-H)", "substrate", 1.5110e-09, 62.5, 2.0, 4.7552e-07, 62.5, 2.0),
    OERxn("Halogenation", "Anodic benzylic fluorination", "substrate", 1.9719e-09, 100.0, 2.0, 4.7552e-07, 100.0, 2.0),
    OERxn("Halogenation", "Br- oxidation / electrophilic bromination", "mediator", 2.0800e-09, 152.0, 1.0, 9.5745e-07, 121.0, 2.0),
    OERxn("Multicomponent coupling", "Sulfonylation of alkenes with sulfinates", "substrate", 1.6849e-09, 62.5, 1.0, 6.9211e-07, 62.5, 1.0),
    OERxn("C-S formation", "Aryl thiocyanation (NH4SCN)", "mediator", 7.8000e-10, 100.0, 1.0, 1.1327e-06, 250.0, 2.0),
    OERxn("Other bond formation", "Anodic C-H phosphonylation of azoles", "substrate", 1.6266e-09, 50.0, 2.0, 4.7552e-07, 50.0, 2.0),
    OERxn("Other bond formation", "N-N azo/pyrazole formation (N-H/N-H)", "substrate", 5.4752e-10, 40.0, 2.0, 1.0144e-06, 40.0, 2.0),
]
