#!/usr/bin/env python3
"""G-DSUB -- the 8 mediated substrate diffusivities in the solver must equal the generated ones.

    cd Section4_Model && python data/check_substrate_D.py
    cd Section4_Model && python data/check_substrate_D.py --negative-control

`data/mediated_substrates.csv` is generated by build_mediated_substrates.py, which computes each
value by Wilke-Chang from a NAMED structure in a NAMED solvent. This gate asserts that
julia/run_mediated.jl actually carries those values -- in BOTH places it uses them, the MedSpec
D_S field and the S("Sub", ...) species entry, which are independent literals that can drift apart.

Before this existed the eight were hand-typed with nothing reproducing them, and three were wrong:
Hofmann 2.00e-9 for a substrate whose WC value is 1.861e-9, NHPI 1.78e-9 against 1.945e-9, and
bromination 6.25e-10 against 9.148e-10 -- 46% low, for a substrate the registry had misnamed.
"""
import csv, io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__)); SEC4 = os.path.dirname(HERE)
REL = 5e-4

def main(neg=False):
    sub = {r["reaction"]: r for r in
           csv.DictReader(io.open(os.path.join(HERE, "mediated_substrates.csv"), encoding="utf-8"))}
    src = io.open(os.path.join(SEC4, "julia", "run_mediated.jl"), encoding="utf-8").read()
    src = "\n".join(re.sub(r"#.*$", "", ln) for ln in src.split("\n"))   # code, not comments
    fails, ok = [], 0
    print("%-46s %11s %11s %11s" % ("reaction", "generated", "MedSpec", "S(\"Sub\")"))
    for label, r in sub.items():
        D = float(r["D_sub_m2s"])
        if neg and label.startswith("HMF"):
            D *= 1.02                                    # perturb the generated side
        esc = re.escape(label)
        m = re.search(r'MedSpec\("%s",\s*[\d.e+-]+,\s*[\d.e+-]+,\s*[\d.e+-]+,\s*\d+,\s*\d+,'
                      r'\s*[\d.]+,\s*[\d.]+,\s*([\d.e+-]+)' % esc, src)
        i = src.find('MedSpec("%s"' % label)
        j = src.find('S("Sub"', i) if i >= 0 else -1
        nxt = src.find('MedSpec("', i + 10) if i >= 0 else -1
        m2 = re.compile(r'S\("Sub",\s*[\d.]+,\s*([\d.e+-]+)').match(src, j) if (j >= 0 and (nxt < 0 or j < nxt)) else None
        if not m or not m2:
            fails.append("%s: could not locate %s in run_mediated.jl -- the code was reworded and "
                         "this check silently stopped testing"
                         % (label, "MedSpec D_S" if not m else 'S("Sub") D')); continue
        a, b = float(m.group(1)), float(m2.group(1))
        bad = abs(a - D) > REL * D or abs(b - D) > REL * D
        print("%-46s %11.4g %11.4g %11.4g%s" % (label[:46], D, a, b, "   <-- MISMATCH" if bad else ""))
        if bad:
            fails.append("%s: generated %.5g, MedSpec has %.5g, S(\"Sub\") has %.5g" % (label, D, a, b))
        else:
            ok += 1
    print()
    if fails:
        if neg:
            fired = any("HMF" in f for f in fails)
            print("G-DSUB control: %s (perturbed generated value was %sdetected)"
                  % ("GOOD" if fired else "BAD", "" if fired else "NOT "))
            raise SystemExit(0 if fired else 1)
        print("G-DSUB: FAIL")
        for x in fails: print("   ", x)
        raise SystemExit(1)
    print("G-DSUB: PASS -- all %d substrate diffusivities match the generated table (Wilke-Chang, or "
          "the measured value where one is page-anchored), in both the MedSpec field and the species "
          "entry" % ok)

if __name__ == "__main__":
    main("--negative-control" in sys.argv)
