"""Reactor-archetype bands in reduced intensification x_hat = delta_batch / delta.

PROVENANCE (state B, DERIVED). Every band edge returned here is computed AT RUNTIME
from the same two inputs the Julia model uses:

  * julia/reactions_table.jl  -- the 50-reaction table (D, nu per row), itself
    generated by data/build_reactions50.py from the page-verified conditions of
    Table S2;
  * julia/correlations.jl     -- the mass-transfer correlations, with their cited
    sources: Levich RDE; Leveque entrance solution for the parallel-plate channel
    (Walsh 2018 review); Eisenberg-Tobias-Wilke (1954) for the rotating cylinder;
    Newman & Thomas-Alyea ch. 17; Pletcher & Walsh.

The Python `delta_eff` below is a line-for-line transcription of the Julia
`delta_eff` in correlations.jl. `verify_against_tier0()` re-derives the Tier-0
matrix from it and asserts agreement with julia/tier0_ec_matrix.csv, so the
transcription cannot silently drift from the model it claims to represent.

WHY THIS MODULE EXISTS. The archetype bands previously drawn on the payoff map
(make_fig_nd.py panel a, duplicated as main-text Fig. 4B-c) were hardcoded as
x_hat = (2.5, 3.5) "stirred", (5, 15) "flow", (30, 100) "thin gap / RDE / RCE".
Two of the three are contradicted by the model: flow spans 3.13-7.90 (median
4.03), and the 30-100 band contains NO archetype at its upper end -- thin gap is
7.89-19.91, RDE 19.03-35.46, RCE 20.21-34.28, and nothing in the 50-reaction set
reaches x_hat = 100. Bands are what a reader uses to answer "what does a flow cell
buy me", so a band placed 2-3x too far right misstates the answer and moves where
the mediated plateau appears to bite. They are therefore computed, never written
down.

delta_batch = 228 um is the :natural archetype of correlations.jl (registry row
"delta (unstirred batch)"), so x_hat = 1 for the unstirred beaker by construction.
"""
import os
import re
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SEC4 = os.path.dirname(HERE)
F_CONST = 96485.33
DELTA_BATCH_UM = 228.0          # :natural in correlations.jl

_RX_RE = re.compile(
    r'OERxn\("([^"]*)",\s*"([^"]*)",\s*"([^"]*)",\s*([-\d.eE+]+),\s*([-\d.eE+]+),'
    r'\s*([-\d.eE+]+),\s*([-\d.eE+]+),\s*([-\d.eE+]+),\s*([-\d.eE+]+)\)')


def load_reactions(path=None):
    """Parse julia/reactions_table.jl -> list of dicts (D and nu in SI units)."""
    path = path or os.path.join(SEC4, "julia", "reactions_table.jl")
    out = []
    for m in _RX_RE.finditer(open(path).read()):
        cls, name, carrier, D, C, n, nu, Csub, nsub = m.groups()
        out.append(dict(cls=cls, name=name, carrier=carrier, D=float(D), C=float(C),
                        n=float(n), nu=float(nu), Csub=float(Csub), nsub=float(nsub)))
    if len(out) != 50:
        raise RuntimeError("expected 50 reactions in reactions_table.jl, got %d" % len(out))
    return out


# ── transcription of julia/correlations.jl ───────────────────────────────────
# These three are EMPIRICAL fits from named papers, not derivations. julia/correlations.jl is
# the primary copy and verify_against_tier0() below asserts this transcription against it, but
# the references belong at the point of use in both:
#
#   Levich  1.61 D^(1/3) nu^(1/6) omega^(-1/2)
#     Bard & Faulkner, "Electrochemical Methods", 2nd edn, Wiley, 2001, p. 30 fn. 11
#     (cross-ref Sect. 9.3.2); coefficient confirmed in Sect. 12.4. The source prints 1.61.
#   Leveque  Sh = 1.85 (Re Sc d_h/L)^(1/3)
#     Pickett & Ong, Electrochim. Acta 1974, 19, 875-882 -- validated in this exact geometry.
#     Their entrance-length correction to L is NOT applied here, which overstates i_lim.
#   Eisenberg-Tobias-Wilke  Sh = 0.0791 Re^0.70 Sc^0.356
#     Eisenberg, Tobias & Wilke, J. Electrochem. Soc. 1954, 101, 306-320,
#     DOI 10.1149/1.2781252. Fitted at Sc ~ 1000-3000; extrapolated here (see G-DSTIR).
def _delta_rde(D, nu, rpm=1600.0):
    omega = 2.0*np.pi*rpm/60.0
    return 1.61*D**(1.0/3.0)*nu**(1.0/6.0)/np.sqrt(omega)


def _km_leveque(D, nu, h, L, u):
    dh = 2.0*h
    Re = u*dh/nu
    Sc = nu/D
    if Re >= 2300.0:
        raise AssertionError("Leveque used outside laminar regime (Re=%.0f)" % Re)
    Sh = 1.85*(Re*Sc*dh/L)**(1.0/3.0)
    return max(Sh*D/dh, D/(h/2.0))          # entrance soln bounded by half-gap film


# The three flow films, adopted 2026-09-07 (locators in correlations.jl): Watkins 2023 SI Table
# S1 parallel H-cell (106.9 um, measured) and ANEC (36.2 um, measured); Mo 2020 microfluidic
# cell derived from its printed 25 um gap and 4 min residence time by the Leveque/half-gap rule.
DELTA_FLOW = 106.9e-6
DELTA_ANEC = 36.2e-6
H_MICRO, TAU_MICRO = 25.0e-6, 4.0 * 60.0      # 25 um gap; 4 min residence time, in s


def _km_micro(D, h=H_MICRO, tau=TAU_MICRO):
    Sh = 1.85*(4.0*h**2/(D*tau))**(1.0/3.0)          # Re Sc d_h/L = 4 h^2/(D tau) exactly
    return max(Sh*D/(2.0*h), D/(h/2.0))


def _km_rce(D, nu, d=0.012, rpm=3000.0):
    U = np.pi*d*rpm/60.0
    Re = U*d/nu
    Sc = nu/D
    return 0.0791*Re**0.70*Sc**0.356*D/d


def delta_eff(key, D, nu):
    """Effective Nernst diffusion-layer thickness [m]. Mirrors correlations.jl."""
    if key == "natural":
        return 228e-6
    if key == "stirred":
        # 200 um, adopted 2026-09-01 (measured, Williams/Manthiram p. 1227). This module is a
        # PYTHON TRANSCRIPTION of julia/correlations.jl and drifted from it when that file
        # moved: verify_against_tier0() detected the disagreement, but nothing called it.
        return 200e-6
    if key == "flow":
        return DELTA_FLOW
    if key == "anec":
        return DELTA_ANEC
    if key == "micro":
        return D/_km_micro(D)
    if key == "rde":
        return _delta_rde(D, nu)
    if key == "rce":
        return D/_km_rce(D, nu)
    raise ValueError("unknown reactor %r" % (key,))


ARCHETYPES = ["natural", "stirred", "flow", "anec", "micro", "rde", "rce"]


def delta_table(rxns=None):
    """{archetype: array of delta_eff in um over the 50 rows}."""
    rxns = rxns or load_reactions()
    return {k: np.array([delta_eff(k, r["D"], r["nu"]) for r in rxns])*1e6
            for k in ARCHETYPES}


def xhat_table(rxns=None, delta_batch_um=DELTA_BATCH_UM):
    d = delta_table(rxns)
    return {k: delta_batch_um/v for k, v in d.items()}


def verify_against_tier0(tol=1e-3):
    """Re-derive Tier-0 i_lim from this module and check julia/tier0_matrix.csv.

    This tests ONE thing: that the Python transcription of the mass-transfer
    correlations reproduces the Julia one. It must therefore compare Fick against
    Fick -- julia/tier0_matrix.csv, the migration-free layer.

    It read julia/tier0_ec_matrix.csv until 2026-08-25, which was the same file
    until the 2026-08-24 one-physics merge made the published matrix full
    Nernst-Planck. After that the comparison was Fick-against-NP and failed by 65%
    on the charged carriers (Kolbe migrates x2.006), so Fig. 4B stopped rendering
    for a reason that had nothing to do with delta_eff.

    Only the 42 substrate/catalyst rows are checked: the 8 mediator rows carry the
    EC' (Saveant/NPP) ceiling, not the Fickian tier-0 value, so they are not a test
    of delta_eff. Returns the worst relative error.
    """
    import csv
    rxns = load_reactions()
    path = os.path.join(SEC4, "julia", "tier0_matrix.csv")
    rows = [{k.strip(): v for k, v in r.items()}
            for r in csv.DictReader(open(path))]
    worst = 0.0
    for r, t in zip(rxns, rows):
        if r["carrier"] == "mediator":
            continue
        for k in ARCHETYPES:
            i = 0.1*r["n"]*F_CONST*r["D"]*r["C"]/delta_eff(k, r["D"], r["nu"])
            worst = max(worst, abs(i - float(t[k]))/float(t[k]))
    if worst > tol:
        raise AssertionError(
            "archetype_bands.delta_eff disagrees with julia/tier0_ec_matrix.csv "
            "by %.2e (tol %.0e) -- the Python transcription has drifted from "
            "correlations.jl" % (worst, tol))
    return worst


# ── the bands actually drawn ─────────────────────────────────────────────────
# (key, label). Ordered left to right in x_hat. RDE and RCE are merged: their
# ranges overlap over 19.0-34.3 and no reader distinguishes them on a log axis.
# Thin gap is kept SEPARATE from RDE/RCE -- lumping them, as the old (30,100)
# band did, hides a factor of two between two different reactor classes.
BAND_SPEC = [("stirred",            ["stirred"],      "stirred\nbatch"),
             ("flow",               ["flow"],         "recirculating\nflow cell"),
             ("anec",               ["anec"],         "ANEC\nflow cell"),
             ("micro",              ["micro"],        "microfluidic\n(25 $\\mu$m)"),
             ("rotating",           ["rde", "rce"],   "RDE / RCE")]


def xhat_bands(rxns=None, delta_batch_um=DELTA_BATCH_UM, verify=True):
    """[(x_lo, x_hi, label, key)] -- min/max over the 50 rows, model-derived.

    A degenerate band (stirred: delta = 200 um for every row, so x_hat = 3.00
    exactly) is returned with x_lo == x_hi; the caller decides how to draw a
    zero-width band.
    """
    if verify:
        verify_against_tier0()
    x = xhat_table(rxns, delta_batch_um)
    out = []
    for key, members, lab in BAND_SPEC:
        v = np.concatenate([x[m] for m in members])
        out.append((float(v.min()), float(v.max()), lab, key))
    return out


def xhat_ceiling(rxns=None, delta_batch_um=DELTA_BATCH_UM):
    """Largest x_hat any archetype reaches over the 50 rows (= thinnest film)."""
    x = xhat_table(rxns, delta_batch_um)
    return float(max(v.max() for v in x.values()))


if __name__ == "__main__":
    print("delta_eff vs tier0_ec_matrix.csv: max rel err %.3e" % verify_against_tier0())
    d = delta_table()
    x = xhat_table()
    print("\n%-9s %-32s %s" % ("archetype", "delta_eff (um)  min/med/max", "x_hat  min/med/max"))
    for k in ARCHETYPES:
        print("%-9s  %8.2f %8.2f %8.2f      %7.2f %7.2f %7.2f"
              % (k, d[k].min(), np.median(d[k]), d[k].max(),
                 x[k].min(), np.median(x[k]), x[k].max()))
    print("\nbands drawn:")
    for lo, hi, lab, key in xhat_bands():
        print("  %-10s x_hat %7.2f - %7.2f   (%s)" % (key, lo, hi, lab.replace("\n", " ")))
    print("\nx_hat ceiling over all archetypes: %.2f" % xhat_ceiling())
