"""model_medians.py — runtime-computed population statistics for the Section 4 figures.

Created to close figure-provenance-audit findings 3, 4 and 5: the generators used to
hardcode `C = 1740` (the i_lim*delta constant), `delta = 14 um` (an "RDE/RCE" anchor
that matches neither archetype), and a catalyst ceiling built from three unsourced
constants (D = 6e-6 cm2/s, n_c = 2, C_cat = 10 mM). Every one of those numbers is
recoverable from files already in the repo, so nothing here is an assumption:

  julia/reactions_table.jl   the 50-reaction table the Julia model itself consumes
                             (D, C, n, nu per row; generated by data/build_reactions50.py
                             from data/reactions_50.csv)
  julia/correlations.jl      the delta_eff correlations, transcribed below verbatim
  julia/tier0_ec_matrix.csv  the production i_lim matrix (Tier-0 Fick for substrate and
                             catalyst rows; EC' solver output for the 8 mediator rows)
  julia/mediated_ec_matrix.csv  the full 8-mediator x 6-reactor EC' solve

`self_check()` reproduces julia/tier0_matrix.csv from the transcribed correlations, so a
drift in either the Julia model or this module is caught at import time.

Nomenclature:
  K  =  0.1 * n * F * D * C     [mA cm^-2 um]   the per-row "nFDC" constant, so that
                                                i_lim(delta) = K / delta_um
"""
import math, os, re
import numpy as np
import pandas as pd

F_CONST = 96485.332
ARCHETYPES = ["natural", "stirred", "flow", "anec", "micro", "rde", "rce"]
ARCH_LABEL = {"natural": "unstirred", "stirred": "stirred", "flow": "flow",
              "anec": "ANEC", "micro": "microfluidic", "rde": "RDE", "rce": "RCE"}

_HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(_HERE)


def _p(*parts):
    return os.path.join(ROOT, *parts)


# ── julia/correlations.jl, transcribed ────────────────────────────────────────
def delta_rde(D, nu, rpm=1600.0):
    omega = 2.0 * math.pi * rpm / 60.0
    return 1.61 * D ** (1 / 3) * nu ** (1 / 6) / math.sqrt(omega)


def km_leveque(D, nu, h, L, u):
    dh = 2.0 * h
    Re = u * dh / nu
    Sc = nu / D
    assert Re < 2300, f"Leveque used outside laminar regime (Re={Re:.0f})"
    Sh = 1.85 * (Re * Sc * dh / L) ** (1 / 3)
    return max(Sh * D / dh, D / (h / 2))


# The three flow films, adopted 2026-09-07 (see correlations.jl for the locators): two MEASURED
# ferricyanide films from Watkins et al., ACS Energy Lett. 2023, 8, 2185, SI Table S1 (parallel
# H-cell 106.9 um; ANEC 36.2 um), and the Mo 2020 microfluidic cell DERIVED from its printed gap
# (25 um) and residence time (4 min) by the Leveque/half-gap rule, whose Leveque number is
# 4 h^2/(D tau) exactly.
DELTA_FLOW = 106.9e-6
DELTA_ANEC = 36.2e-6
H_MICRO, TAU_MICRO = 25.0e-6, 4.0 * 60.0      # 25 um gap; 4 min residence time, in s


def km_micro(D, h=H_MICRO, tau=TAU_MICRO):
    Sh = 1.85 * (4.0 * h ** 2 / (D * tau)) ** (1 / 3)
    return max(Sh * D / (2.0 * h), D / (h / 2.0))


def km_rce(D, nu, d=0.012, rpm=3000.0):
    U = math.pi * d * rpm / 60.0
    Re = U * d / nu
    Sc = nu / D
    return 0.0791 * Re ** 0.70 * Sc ** 0.356 * D / d


def delta_eff(key, D, nu):
    """Effective Nernst diffusion-layer thickness [m], per julia/correlations.jl."""
    if key == "natural":
        return 228e-6
    if key == "stirred":
        # the stirred film. ADOPTED 200 um on 2026-09-01 (author decision). The retired 100 um was an assumption whose inherited citation had been WITHDRAWN -- no passage in Pletcher & Walsh giving ~100 um for a magnetically stirred cell could be located. 200 +/- 7 um is MEASURED: Williams, Corbin, Zeng, Lazouski, Yang & Manthiram, Sustain. Energy Fuels 2019, 3, 1225-1232, p. 1227, a planar electrode in a gas-bubbled cell, back-calculated from the ferricyanide limiting current. It is a proxy, not this system: O2 diffuses about twice as fast as these organics, and a convective film thickens with D (D^(1/3) laminar, D^(1/2) penetration), so the real layer should if anything be THINNER, by ~20-30 pct, and the adopted value is conservative (it lowers the ceilings). Corrected in chemistry audit pass 3; it had the direction reversed.
        return 200e-6
    if key == "flow":
        return DELTA_FLOW
    if key == "anec":
        return DELTA_ANEC
    if key == "micro":
        return D / km_micro(D)
    if key == "rde":
        return delta_rde(D, nu)
    if key == "rce":
        return D / km_rce(D, nu)
    raise KeyError(key)


# ── the 50-reaction table, read from the Julia model's own input ──────────────
_OERXN = re.compile(
    r'OERxn\("([^"]*)",\s*"([^"]*)",\s*"([^"]*)",\s*([-\d.eE+]+),\s*([-\d.eE+]+),'
    r'\s*([-\d.eE+]+),\s*([-\d.eE+]+),\s*([-\d.eE+]+),\s*([-\d.eE+]+)\)')


def load_reactions():
    src = open(_p("julia", "reactions_table.jl")).read()
    rows = [dict(cls=m[0], name=m[1], carrier=m[2], D=float(m[3]), C=float(m[4]),
                 n=float(m[5]), nu=float(m[6]), Csub=float(m[7]), nsub=float(m[8]))
            for m in _OERXN.findall(src)]
    df = pd.DataFrame(rows)
    assert len(df) == 50, f"expected 50 reactions, parsed {len(df)}"
    # K = 0.1 n F D C  [mA cm^-2 um]  ->  i_lim(delta_um) = K / delta_um
    df["K"] = 0.1 * df.n * F_CONST * df.D * df.C / 1e-6
    for k in ARCHETYPES:
        df["d_" + k] = [delta_eff(k, r.D, r.nu) * 1e6 for r in df.itertuples()]
        df["i_" + k] = df.K / df["d_" + k]
    return df


RXN = load_reactions()
TIER0_EC = pd.read_csv(_p("julia", "tier0_ec_matrix.csv"))
MEDIATED = pd.read_csv(_p("julia", "mediated_ec_matrix.csv"))


def self_check(tol=1e-3):
    """Reproduce julia/tier0_matrix.csv from the transcribed correlations."""
    ref = pd.read_csv(_p("julia", "tier0_matrix.csv"))
    for k in ARCHETYPES:
        rel = np.abs(RXN["i_" + k].values - ref[k].values) / np.maximum(ref[k].values, 1e-12)
        assert rel.max() < tol, f"{k}: max rel err {rel.max():.2e} vs tier0_matrix.csv"
    assert len(TIER0_EC) == 50
    return True


self_check()


# ── population statistics ─────────────────────────────────────────────────────
# Rows whose electron count is the charge the exemplar passes through a CHAIN (kind "chain" in
# data/reaction_stoichiometry.csv, the table the SI prints as Table S10). They are solved and
# tabulated like every other row and counted in every all-fifty statistic. They are left out of
# CLASS statistics, because a class median of ceilings would mix a current normalised by passed
# charge with currents that are stoichiometric in the product.
import csv as _csv
CHAIN = frozenset(r["reaction"] for r in _csv.DictReader(open(_p("data", "reaction_stoichiometry.csv"), encoding="utf8"))
                  if r["kind"] == "chain")
assert CHAIN and CHAIN <= set(RXN.name), "chain rows of reaction_stoichiometry.csv are not rows of the table"


def pop(carrier=None, chains=False):
    """Rows of the 50-reaction table for one carrier class (or all 50).

    A class selection leaves the chain rows out unless chains=True; the all-fifty selection
    never drops a row."""
    if carrier is None:
        return RXN
    p = RXN[RXN.carrier == carrier]
    return p if chains else p[~p.name.isin(CHAIN)]


def class_matrix(carrier, chains=False):
    """Published-matrix rows of one carrier class, chain rows left out unless asked for."""
    t = TIER0_EC[TIER0_EC.carrier == carrier]
    return t if chains else t[~t.reaction.isin(CHAIN)]


def K_stats(carrier=None, lo=10, hi=90):
    """Median and lo/hi percentiles of K = 0.1 n F D C  [mA cm^-2 um]."""
    v = pop(carrier).K.values
    return dict(median=float(np.median(v)), lo=float(np.percentile(v, lo)),
                hi=float(np.percentile(v, hi)), min=float(v.min()), max=float(v.max()),
                n=int(v.size), lo_pct=lo, hi_pct=hi)


def delta_median(key, carrier=None):
    """Median effective film thickness [um] for one archetype over a population."""
    return float(np.median(pop(carrier)["d_" + key].values))


def delta_range(key, carrier=None):
    d = pop(carrier)["d_" + key].values
    return float(d.min()), float(d.max())


def ilim_median(key, carrier=None, production=True):
    """Median i_lim [mA cm^-2] for one archetype.

    production=True uses julia/tier0_ec_matrix.csv, the matrix the figures and the SI
    quote (identical to Tier-0 Fick for the 42 substrate/catalyst rows, EC'-solver
    output for the 8 mediator rows). production=False uses pure Fick for all 50.
    """
    if not production:
        return float(np.median(pop(carrier)["i_" + key].values))
    t = TIER0_EC if carrier is None else class_matrix(carrier)
    return float(np.median(t[key].values))


def guide_constant(carrier=None, production=True):
    """Constant of the 1/delta guide line, anchored at the stirred-batch archetype.

    delta is exactly 200 um for every row in the stirred archetype, so the median of
    i_lim*delta there is unambiguous and needs no assumption about which row is typical.
    Replaces the hardcoded `C = 1740`.
    """
    return ilim_median("stirred", carrier, production) * 200.0


def mediated_delta_slopes():
    """log-log slope d(ln i_EC)/d(ln delta) per mediator, over converged rows only.

    0 => delta-insensitive (Saveant reaction-layer plateau); -1 => pure Fick.
    Rows flagged 'wall' in mediated_ec_matrix.csv (Newton hit a wall, i_EC below the
    commuting bound) are excluded — that is the model's own convergence flag, not a
    selection made for the figure.
    """
    out = {}
    ok = MEDIATED[MEDIATED.flag == "ok"]
    for name, g in ok.groupby("reaction"):
        slope = float(np.polyfit(np.log(g.delta_um.values), np.log(g.i_ec_mAcm2.values), 1)[0])
        out[name] = dict(slope=slope, xk_um=float(g.xk_um.iloc[0]),
                         i_sav=float(g.i_saveant_mAcm2.iloc[0]),
                         i_min=float(g.i_ec_mAcm2.min()), i_max=float(g.i_ec_mAcm2.max()),
                         n=int(len(g)), delta=g.delta_um.values, i_ec=g.i_ec_mAcm2.values)
    return out


if __name__ == "__main__":
    print("self_check OK\n")
    print("populations:", RXN.carrier.value_counts().to_dict(), "\n")
    print("K = 0.1 n F D C  [mA cm^-2 um]")
    for c in (None, "substrate", "catalyst", "mediator"):
        s = K_stats(c)
        print(f"  {str(c):10s} n={s['n']:2d}  p10 {s['lo']:10.2f}  median {s['median']:10.2f}  p90 {s['hi']:10.2f}")
    print("\narchetype delta medians [um] and production i_lim medians [mA cm^-2]")
    for k in ARCHETYPES:
        print(f"  {k:8s} all50 delta {delta_median(k):7.2f}  i {ilim_median(k):8.2f}"
              f"   | substrate delta {delta_median(k,'substrate'):7.2f} i {ilim_median(k,'substrate'):8.2f}"
              f"   | catalyst delta {delta_median(k,'catalyst'):7.2f} i {ilim_median(k,'catalyst'):8.2f}")
    print(f"\nguide constant, all 50   = {guide_constant():.2f} mA cm^-2 um")
    print(f"guide constant, substrate= {guide_constant('substrate'):.2f}")
    print(f"guide constant, catalyst = {guide_constant('catalyst'):.2f}")
    print("\nmediated delta-sensitivity:")
    for nm, d in sorted(mediated_delta_slopes().items(), key=lambda kv: kv[1]["slope"]):
        print(f"  {nm[:44]:46s} slope {d['slope']:+.3f}  x_k {d['xk_um']:7.2f} um  "
              f"i_EC {d['i_min']:8.2f}-{d['i_max']:9.1f}  (n={d['n']})")
